steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v3.0.0
    env:
      CC_TEST_REPORTER_ID: 29648b96dc8ebbc5aaae8c4fca7853936108a803db7539ed0ebf51380922a3d8
    with:
      coverageCommand: rspec
      debug: true
